=== cosniq/projects/Motion Based Application Thesis/hivemq-4.8.0/extensions/hivemq-enterprise-security-extension/conf/ese-file-realm.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="ese-file-realm" type="authFileConfigurationEntity"/>

  <xs:complexType name="authFileConfigurationEntity">
    <xs:choice>
      <xs:sequence>
        <xs:element name="mqtt" type="mqttEntity"/>
        <xs:element name="control-center" type="controlCenterEntity" minOccurs="0"/>
      </xs:sequence>
      <xs:sequence>
        <xs:element name="control-center" type="controlCenterEntity"/>
        <xs:element name="mqtt" type="mqttEntity" minOccurs="0"/>
      </xs:sequence>
    </xs:choice>

    <xs:attribute name="version" type="xs:string"/>
  </xs:complexType>

  <xs:complexType name="mqttEntity">
    <xs:all>
      <xs:element name="users" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="user" type="userEntity" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="roles" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="role" type="roleEntity" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="userEntity">
    <xs:all>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="permissions" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="permission" type="permissionEntity" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="permissionEntity">
    <xs:all>
      <xs:element name="topic" type="xs:string" default=""/>
      <xs:element name="activity" type="mqttActivity"/>
      <xs:element name="qos" type="qos"/>
      <xs:element name="retain" type="retain" default="NOT_RETAINED" minOccurs="0"/>
      <xs:element name="shared-subscription" type="sharedSubscription" default="NOT_SHARED" minOccurs="0"/>
      <xs:element name="shared-group" type="xs:string" default="" minOccurs="0"/>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="roleEntity">
    <xs:all>
      <xs:element name="id">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="permissions" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="permission" type="permissionEntity" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="controlCenterEntity">
    <xs:all>
      <xs:element name="users" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="user" type="ccUserEntity" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
      <xs:element name="roles" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="role" type="ccRoleEntity" minOccurs="0" maxOccurs="unbounded"/>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="ccUserEntity">
    <xs:all>
      <xs:element name="name">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="permissions" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="permission" minOccurs="0" maxOccurs="unbounded">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:minLength value="1"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:complexType name="ccRoleEntity">
    <xs:all>
      <xs:element name="id">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="permissions" minOccurs="0">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="permission" minOccurs="0" maxOccurs="unbounded">
              <xs:simpleType>
                <xs:restriction base="xs:string">
                  <xs:minLength value="1"/>
                </xs:restriction>
              </xs:simpleType>
            </xs:element>
          </xs:sequence>
        </xs:complexType>
      </xs:element>
    </xs:all>
  </xs:complexType>

  <xs:simpleType name="mqttActivity">
    <xs:restriction base="xs:string">
      <xs:enumeration value="PUBLISH"/>
      <xs:enumeration value="SUBSCRIBE"/>
      <xs:enumeration value="ALL"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="qos">
    <xs:restriction base="xs:string">
      <xs:enumeration value="ZERO"/>
      <xs:enumeration value="ONE"/>
      <xs:enumeration value="TWO"/>
      <xs:enumeration value="ZERO_ONE"/>
      <xs:enumeration value="ZERO_TWO"/>
      <xs:enumeration value="ONE_TWO"/>
      <xs:enumeration value="ALL"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="retain">
    <xs:restriction base="xs:string">
      <xs:enumeration value="RETAINED"/>
      <xs:enumeration value="NOT_RETAINED"/>
      <xs:enumeration value="ALL"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="sharedSubscription">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SHARED"/>
      <xs:enumeration value="NOT_SHARED"/>
      <xs:enumeration value="ALL"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>

=== cosniq/projects/Motion Based Application Thesis/hivemq-4.8.0/extensions/hivemq-enterprise-security-extension/conf/examples/file-realm/ese-file-realm.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<ese-file-realm xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="ese-file-realm.xsd">
    <mqtt>
        <!-- users are fetched via AUTHENTICATION_KEY-->
        <users>
            <user>
                <name>admin-user</name>
                <permissions>
                    <permission>
                        <topic>#</topic>
                        <qos>ALL</qos>
                        <activity>ALL</activity>
                        <retain>ALL</retain>
                        <shared-subscription>ALL</shared-subscription>
                        <shared-group>group-1</shared-group>
                    </permission>
                </permissions>
            </user>
        </users>

        <!-- roles are fetched via AUTHENTICATION_ROLE_KEY-->
        <roles>
            <role>
                <id>role-1</id>
                <permissions>
                    <permission>
                        <topic>topic-1</topic>
                        <qos>ALL</qos>
                        <activity>SUBSCRIBE</activity>
                    </permission>
                </permissions>
            </role>
        </roles>
    </mqtt>


    <control-center>
        <!-- list of available permissions:
               https://www.hivemq.com/docs/ese/latest/enterprise-security-extension/ese.html#control-center-access-control-permissions -->
        <users>
            <user>
                <name>cc-admin-user</name>
                <permissions>
                    <permission>HIVEMQ_SUPER_ADMIN</permission>
                </permissions>
            </user>
        </users>

        <roles>
            <role>
                <id>cc-backup-only-role</id>
                <permissions>
                    <permission>HIVEMQ_VIEW_PAGE_BACKUP</permission>
                </permissions>
            </role>
        </roles>
    </control-center>
</ese-file-realm>
